INSERT INTO AYAH VALUES(1, 'ذلك الكتاب', 2, 2);
INSERT INTO AYAH VALUES(2, 'لاريب فيه', 2, 2);
INSERT INTO AYAH VALUES(3, 'هدى ', 2, 2);
INSERT INTO AYAH VALUES(4, 'للمتقين', 2, 2);
INSERT INTO AYAH VALUES(5, 'على هدى ', 5, 2);
INSERT INTO AYAH VALUES(6, 'ختم الله', 7, 2);
INSERT INTO AYAH VALUES(7, 'غشاوة ', 7, 2);
INSERT INTO AYAH VALUES(8, 'يخادعون', 9, 2);
INSERT INTO AYAH VALUES(9, 'مرض', 10, 2);
INSERT INTO AYAH VALUES(10, 'خلوا إلى شياطينهم', 14, 2);
INSERT INTO AYAH VALUES(11, 'يمدّهم ', 15, 2);
INSERT INTO AYAH VALUES(12, 'طغيانهم', 15, 2);
INSERT INTO AYAH VALUES(13, 'يعمهون', 15, 2);
INSERT INTO AYAH VALUES(14, 'مثلُهُم ', 17, 2);
INSERT INTO AYAH VALUES(15, 'استوقد نارا', 17, 2);
INSERT INTO AYAH VALUES(16, 'بكمٌ', 18, 2);
INSERT INTO AYAH VALUES(17, 'كصيّبٍ', 19, 2);
INSERT INTO AYAH VALUES(18, 'يخطفُ أبصارهم', 20, 2);
INSERT INTO AYAH VALUES(19, 'قاموا ', 20, 2);
INSERT INTO AYAH VALUES(20, 'الأرضَ فراشاً', 22, 2);
INSERT INTO AYAH VALUES(21, 'السماء بناءً', 22, 2);
INSERT INTO AYAH VALUES(22, 'أنداداً', 22, 2);
INSERT INTO AYAH VALUES(23, 'ادعوا شهدائكم ', 23, 2);
INSERT INTO AYAH VALUES(24, 'متشابها', 25, 2);
INSERT INTO AYAH VALUES(25, 'استوى إلى السماء', 29, 2);
INSERT INTO AYAH VALUES(26, 'فسواهن ', 29, 2);
INSERT INTO AYAH VALUES(27, 'يَسفك الدّماء', 30, 2);
INSERT INTO AYAH VALUES(28, 'نسبّح بحمدك', 30, 2);
INSERT INTO AYAH VALUES(29, 'نقدس لك', 30, 2);
INSERT INTO AYAH VALUES(30, 'اسجدوا لآدم ', 34, 2);
INSERT INTO AYAH VALUES(31, 'رغداً', 35, 2);
INSERT INTO AYAH VALUES(32, 'فأزلّهما الشّيطان', 36, 2);
INSERT INTO AYAH VALUES(33, 'إسرائيل', 40, 2);
INSERT INTO AYAH VALUES(34, 'فارهبونِ', 40, 2);
INSERT INTO AYAH VALUES(35, 'ولاتلبِسوا ', 42, 2);
INSERT INTO AYAH VALUES(36, 'بالبرّ', 44, 2);
INSERT INTO AYAH VALUES(37, 'وإنها لكبيرة ', 45, 2);
INSERT INTO AYAH VALUES(38, 'الخاشعين', 45, 2);
INSERT INTO AYAH VALUES(39, 'يظنّون', 46, 2);
INSERT INTO AYAH VALUES(40, 'العالمين', 47, 2);
INSERT INTO AYAH VALUES(41, 'لاتجزي نفسٌ', 48, 2);
INSERT INTO AYAH VALUES(42, 'عدلٌ', 48, 2);
INSERT INTO AYAH VALUES(43, 'يسومونكم', 49, 2);
INSERT INTO AYAH VALUES(44, 'يستحيون نسائكم', 49, 2);
INSERT INTO AYAH VALUES(45, 'بلاءٌ', 49, 2);
INSERT INTO AYAH VALUES(46, 'فَرَقنا', 50, 2);
INSERT INTO AYAH VALUES(47, 'اتخذتم العجل ', 51, 2);
INSERT INTO AYAH VALUES(48, 'الفرقان', 53, 2);
INSERT INTO AYAH VALUES(49, 'بارئكم ', 54, 2);
INSERT INTO AYAH VALUES(50, 'فاقتلوا', 54, 2);
INSERT INTO AYAH VALUES(51, 'جهرةً', 55, 2);
INSERT INTO AYAH VALUES(52, 'الصّاعقة', 55, 2);
INSERT INTO AYAH VALUES(53, 'الغمام', 57, 2);
INSERT INTO AYAH VALUES(54, 'المنّ ', 57, 2);
INSERT INTO AYAH VALUES(55, 'والسلوى', 57, 2);
INSERT INTO AYAH VALUES(56, 'رغدا', 58, 2);
INSERT INTO AYAH VALUES(57, 'قولوا  حِطّة', 58, 2);
INSERT INTO AYAH VALUES(58, 'رجْزًا ', 59, 2);
INSERT INTO AYAH VALUES(59, 'فانفجرت', 60, 2);
INSERT INTO AYAH VALUES(60, 'مشربهم ', 60, 2);
INSERT INTO AYAH VALUES(61, 'لا تعثوا في الأرض', 60, 2);
INSERT INTO AYAH VALUES(62, 'مفسدين ', 60, 2);
INSERT INTO AYAH VALUES(63, 'فومها ', 61, 2);
INSERT INTO AYAH VALUES(64, 'ضُربت عليهم ', 61, 2);
INSERT INTO AYAH VALUES(65, 'الذلّة ', 61, 2);
INSERT INTO AYAH VALUES(66, 'المسكنة', 61, 2);
INSERT INTO AYAH VALUES(67, 'باءوا بغضب', 61, 2);
INSERT INTO AYAH VALUES(68, 'هادوا', 62, 2);
INSERT INTO AYAH VALUES(69, 'الصّابئين  ', 62, 2);
INSERT INTO AYAH VALUES(70, 'ميثاقكم ', 63, 2);
INSERT INTO AYAH VALUES(71, 'خاسئين ', 65, 2);
INSERT INTO AYAH VALUES(72, 'فجعلناها نكالا ', 66, 2);
INSERT INTO AYAH VALUES(73, 'هزوا ', 67, 2);
INSERT INTO AYAH VALUES(74, 'لا فارض و لا بكر', 68, 2);
INSERT INTO AYAH VALUES(75, 'عوان بين ذلك ', 68, 2);
INSERT INTO AYAH VALUES(76, 'فاقع لونها ', 69, 2);
INSERT INTO AYAH VALUES(77, 'لا ذلول', 71, 2);
INSERT INTO AYAH VALUES(78, 'تُثير الأرض ', 71, 2);
INSERT INTO AYAH VALUES(79, 'الحرث ', 71, 2);
INSERT INTO AYAH VALUES(80, 'مسلّمة ', 71, 2);
INSERT INTO AYAH VALUES(81, 'لا شية فيها ', 71, 2);
INSERT INTO AYAH VALUES(82, 'فادّارأتم فيها ', 71, 2);
INSERT INTO AYAH VALUES(83, 'يتفجّر', 74, 2);
INSERT INTO AYAH VALUES(84, 'يشّقق  ', 74, 2);
INSERT INTO AYAH VALUES(85, 'يحرّفونه ', 75, 2);
INSERT INTO AYAH VALUES(86, 'خلا بعضهم ', 76, 2);
INSERT INTO AYAH VALUES(87, 'فتح الله عليكم ', 76, 2);
INSERT INTO AYAH VALUES(88, 'أمّيون ', 78, 2);
INSERT INTO AYAH VALUES(89, 'أمانيّ ', 78, 2);
INSERT INTO AYAH VALUES(90, 'فويل ', 79, 2);
INSERT INTO AYAH VALUES(91, 'كسب سيّئة ', 81, 2);
INSERT INTO AYAH VALUES(92, 'أحاطت به ', 81, 2);
INSERT INTO AYAH VALUES(93, 'تظاهرون عليهم ', 85, 2);
INSERT INTO AYAH VALUES(94, 'أُسارى ', 85, 2);
INSERT INTO AYAH VALUES(95, 'تفادوهم', 85, 2);
INSERT INTO AYAH VALUES(96, 'خزي', 85, 2);
INSERT INTO AYAH VALUES(97, 'قفّينا من بعده بالرّسل', 87, 2);
INSERT INTO AYAH VALUES(98, 'بروح القدس  ', 87, 2);
INSERT INTO AYAH VALUES(99, 'قلوبنا غلف', 88, 2);
INSERT INTO AYAH VALUES(100, 'يستفتحون ', 89, 2);
INSERT INTO AYAH VALUES(101, 'اشتروا به أنفسهم ', 90, 2);
INSERT INTO AYAH VALUES(102, 'بغيا ', 90, 2);
INSERT INTO AYAH VALUES(103, 'فباءوا بغضب', 90, 2);
INSERT INTO AYAH VALUES(104, 'اتخذتم العجل', 92, 2);
INSERT INTO AYAH VALUES(105, 'العجل ', 93, 2);
INSERT INTO AYAH VALUES(106, 'لو يُعمّر', 96, 2);
INSERT INTO AYAH VALUES(107, 'نبذه  ', 100, 2);
INSERT INTO AYAH VALUES(108, 'تتلوا الشّياطين', 102, 2);
INSERT INTO AYAH VALUES(109, 'نحن فتنة ', 102, 2);
INSERT INTO AYAH VALUES(110, 'خَلاق ', 102, 2);
INSERT INTO AYAH VALUES(111, 'شروا به أنفسهم ', 102, 2);
INSERT INTO AYAH VALUES(112, 'لا تقولوا  راعنا ', 104, 2);
INSERT INTO AYAH VALUES(113, 'قولوا  انظرنا ', 104, 2);
INSERT INTO AYAH VALUES(114, 'ما ننسخ من آية ', 106, 2);
INSERT INTO AYAH VALUES(115, 'نُنْسِها ', 106, 2);
INSERT INTO AYAH VALUES(116, 'وليّ', 107, 2);
INSERT INTO AYAH VALUES(117, 'سواء السبيل ', 108, 2);
INSERT INTO AYAH VALUES(118, 'أمانيّهُم ', 111, 2);
INSERT INTO AYAH VALUES(119, 'أسلم وجهه لله ', 112, 2);
INSERT INTO AYAH VALUES(120, 'خِزيٌ', 114, 2);
INSERT INTO AYAH VALUES(121, 'فثمّ وجه الله ', 115, 2);
INSERT INTO AYAH VALUES(122, 'سُبحانه ', 116, 2);
INSERT INTO AYAH VALUES(123, 'له قانتون ', 116, 2);
INSERT INTO AYAH VALUES(124, 'بديع ..', 117, 2);
INSERT INTO AYAH VALUES(125, 'قضى أمرا ', 117, 2);
INSERT INTO AYAH VALUES(126, 'كنْ فيكون ', 117, 2);
INSERT INTO AYAH VALUES(127, 'العالمين ', 122, 2);
INSERT INTO AYAH VALUES(128, 'لا تجزي نفسٌ', 123, 2);
INSERT INTO AYAH VALUES(129, 'عدّلٌ', 123, 2);
INSERT INTO AYAH VALUES(130, 'ابتلى ', 124, 2);
INSERT INTO AYAH VALUES(131, 'بكلماتٍ ', 124, 2);
INSERT INTO AYAH VALUES(132, 'فأتمّهنّ', 124, 2);
INSERT INTO AYAH VALUES(133, 'مثابةً للنّاس ', 125, 2);
INSERT INTO AYAH VALUES(134, 'عهدنا', 125, 2);
INSERT INTO AYAH VALUES(135, 'بيْتِيَ', 125, 2);
INSERT INTO AYAH VALUES(136, 'أضطرّه ', 126, 2);
INSERT INTO AYAH VALUES(137, 'مسلمين لك', 128, 2);
INSERT INTO AYAH VALUES(138, 'أرنا مناسكنا ', 128, 2);
INSERT INTO AYAH VALUES(139, 'يُزكّيهم ', 129, 2);
INSERT INTO AYAH VALUES(140, 'يرغب عنْ . .', 130, 2);
INSERT INTO AYAH VALUES(141, 'سفِه نفسه', 130, 2);
INSERT INTO AYAH VALUES(142, 'أسلِم ', 131, 2);
INSERT INTO AYAH VALUES(143, 'الدّين', 132, 2);
INSERT INTO AYAH VALUES(144, 'خلت ', 134, 2);
INSERT INTO AYAH VALUES(145, 'حنيفا', 135, 2);
INSERT INTO AYAH VALUES(146, 'الأسباط', 136, 2);
INSERT INTO AYAH VALUES(147, 'صبغة الله ', 138, 2);
INSERT INTO AYAH VALUES(148, 'السّفهاء ', 142, 2);
INSERT INTO AYAH VALUES(149, 'ما ولاّهم ؟', 142, 2);
INSERT INTO AYAH VALUES(150, 'عن قِبلتهم ', 142, 2);
INSERT INTO AYAH VALUES(151, 'أمّة وسطا', 143, 2);
INSERT INTO AYAH VALUES(152, 'ينقلب على عقبيه', 143, 2);
INSERT INTO AYAH VALUES(153, 'لَكبيرةً', 143, 2);
INSERT INTO AYAH VALUES(154, 'ليضيع إيمانكم ', 143, 2);
INSERT INTO AYAH VALUES(155, 'شطر المسجد الحرام ', 144, 2);
INSERT INTO AYAH VALUES(156, 'المُمترين', 147, 2);
INSERT INTO AYAH VALUES(157, 'يُزكّيكم', 151, 2);
INSERT INTO AYAH VALUES(158, 'الكتاب و الحكمة ', 151, 2);
INSERT INTO AYAH VALUES(159, 'لَنبْلُونّكم ', 155, 2);
INSERT INTO AYAH VALUES(160, 'صلوات من رّبهم ', 157, 2);
INSERT INTO AYAH VALUES(161, 'شعائر الله ', 158, 2);
INSERT INTO AYAH VALUES(162, 'اعتمر', 158, 2);
INSERT INTO AYAH VALUES(163, 'فلا جناح عليه ', 158, 2);
INSERT INTO AYAH VALUES(164, 'يطّوّف بهما ', 158, 2);
INSERT INTO AYAH VALUES(165, 'يلعنهم الله ', 159, 2);
INSERT INTO AYAH VALUES(166, 'يُنْظَرون', 162, 2);
INSERT INTO AYAH VALUES(167, 'بثّ فيها ', 164, 2);
INSERT INTO AYAH VALUES(168, 'تصريف الرّياح', 164, 2);
INSERT INTO AYAH VALUES(169, 'أندادا ', 165, 2);
INSERT INTO AYAH VALUES(170, 'تقطّعت بهم الأسباب ', 166, 2);
INSERT INTO AYAH VALUES(171, 'كرّة ', 167, 2);
INSERT INTO AYAH VALUES(172, 'حسرات', 167, 2);
INSERT INTO AYAH VALUES(173, 'خطوات الشيطان ', 168, 2);
INSERT INTO AYAH VALUES(174, 'يأمركم بالسّوء', 169, 2);
INSERT INTO AYAH VALUES(175, 'الفحشاء', 169, 2);
INSERT INTO AYAH VALUES(176, 'ألفينا ', 170, 2);
INSERT INTO AYAH VALUES(177, 'ينْعِق ', 171, 2);
INSERT INTO AYAH VALUES(178, 'بُكمٌ', 171, 2);
INSERT INTO AYAH VALUES(179, 'الدم ', 173, 2);
INSERT INTO AYAH VALUES(180, 'لحم الخنزير', 173, 2);
INSERT INTO AYAH VALUES(181, 'ما أهلّ به لغير الله ', 173, 2);
INSERT INTO AYAH VALUES(182, 'اضطرّ', 173, 2);
INSERT INTO AYAH VALUES(183, 'غير باغٍ', 173, 2);
INSERT INTO AYAH VALUES(184, 'و لا عادٍ', 173, 2);
INSERT INTO AYAH VALUES(185, 'ثمنا قليلا ', 174, 2);
INSERT INTO AYAH VALUES(186, 'لا يزكّيهم ', 174, 2);
INSERT INTO AYAH VALUES(187, 'شقاقٍ بعيد', 176, 2);
INSERT INTO AYAH VALUES(188, 'البِرّ', 177, 2);
INSERT INTO AYAH VALUES(189, 'ابن السّبيل', 177, 2);
INSERT INTO AYAH VALUES(190, 'في الرّقاب ', 177, 2);
INSERT INTO AYAH VALUES(191, 'الصّابرين', 177, 2);
INSERT INTO AYAH VALUES(192, 'البأساء و الضّرّاء ', 177, 2);
INSERT INTO AYAH VALUES(193, 'حين البأس', 177, 2);
INSERT INTO AYAH VALUES(194, 'كُتب عليكم ', 178, 2);
INSERT INTO AYAH VALUES(195, 'عُفِي له من أخيه ', 178, 2);
INSERT INTO AYAH VALUES(196, 'ترك خيرا', 180, 2);
INSERT INTO AYAH VALUES(197, 'الوصيّة ', 180, 2);
INSERT INTO AYAH VALUES(198, 'جنفا ', 182, 2);
INSERT INTO AYAH VALUES(199, 'إثما ', 182, 2);
INSERT INTO AYAH VALUES(200, 'يُطيقونه', 184, 2);
INSERT INTO AYAH VALUES(201, 'تطوّع خيرا', 184, 2);
INSERT INTO AYAH VALUES(202, 'لتكبّروا الله', 185, 2);
INSERT INTO AYAH VALUES(203, 'الرّفث', 187, 2);
INSERT INTO AYAH VALUES(204, 'هنّ لباس لكم ', 187, 2);
INSERT INTO AYAH VALUES(205, 'حدود الله ', 187, 2);
INSERT INTO AYAH VALUES(206, 'تدلوا بها ', 188, 2);
INSERT INTO AYAH VALUES(207, 'ثقفتموهم ', 191, 2);
INSERT INTO AYAH VALUES(208, 'الفتنة ', 191, 2);
INSERT INTO AYAH VALUES(209, 'عند المسجد الحرام ', 191, 2);
INSERT INTO AYAH VALUES(210, 'الحُرُمات ', 194, 2);
INSERT INTO AYAH VALUES(211, 'التّهلُكة ', 195, 2);
INSERT INTO AYAH VALUES(212, 'اُحصِرتم ', 196, 2);
INSERT INTO AYAH VALUES(213, 'فما استيسر', 196, 2);
INSERT INTO AYAH VALUES(214, 'من الهدْي ', 196, 2);
INSERT INTO AYAH VALUES(215, 'لا تحلقوا رءوسكم ', 196, 2);
INSERT INTO AYAH VALUES(216, 'يبلغ الهدي محلّه ', 196, 2);
INSERT INTO AYAH VALUES(217, 'ففِدية', 196, 2);
INSERT INTO AYAH VALUES(218, 'نُسُك', 196, 2);
INSERT INTO AYAH VALUES(219, 'من الهدْي', 196, 2);
INSERT INTO AYAH VALUES(220, 'فَرَضَ  ', 197, 2);
INSERT INTO AYAH VALUES(221, 'فلا رفث', 197, 2);
INSERT INTO AYAH VALUES(222, 'لا جدال في الحجّ', 197, 2);
INSERT INTO AYAH VALUES(223, 'جُناحٌ', 198, 2);
INSERT INTO AYAH VALUES(224, 'فضلا', 198, 2);
INSERT INTO AYAH VALUES(225, 'أفضتم', 198, 2);
INSERT INTO AYAH VALUES(226, 'المشعر الحرام ', 198, 2);
INSERT INTO AYAH VALUES(227, 'مناسككم ', 200, 2);
INSERT INTO AYAH VALUES(228, 'خلاق ', 200, 2);
INSERT INTO AYAH VALUES(229, 'في الدّنيا حسنة ', 201, 2);
INSERT INTO AYAH VALUES(230, 'في الآخرة حسنة ', 201, 2);
INSERT INTO AYAH VALUES(231, 'ألدّ الخصام ', 204, 2);
INSERT INTO AYAH VALUES(232, 'الحرث', 205, 2);
INSERT INTO AYAH VALUES(233, 'أخذته العزّة بالإثم ', 206, 2);
INSERT INTO AYAH VALUES(234, 'فحسبه جهنّم ', 206, 2);
INSERT INTO AYAH VALUES(235, 'لبئس المِهاد', 206, 2);
INSERT INTO AYAH VALUES(236, 'يشري نفسه ', 207, 2);
INSERT INTO AYAH VALUES(237, 'في السلم كافّة ', 208, 2);
INSERT INTO AYAH VALUES(238, 'خطوات الشيطان ', 208, 2);
INSERT INTO AYAH VALUES(239, 'زللتم ', 209, 2);
INSERT INTO AYAH VALUES(240, 'ظلل من الغمام ', 210, 2);
INSERT INTO AYAH VALUES(241, 'بغير حساب', 212, 2);
INSERT INTO AYAH VALUES(242, 'بغيا بينهم ', 213, 2);
INSERT INTO AYAH VALUES(243, 'مثل الذين خلوا ', 214, 2);
INSERT INTO AYAH VALUES(244, 'البأساء و الضّرّاء ', 214, 2);
INSERT INTO AYAH VALUES(245, 'زُلزلوا ', 214, 2);
INSERT INTO AYAH VALUES(246, 'كُره لكم ', 216, 2);
INSERT INTO AYAH VALUES(247, 'كبيرٌ', 217, 2);
INSERT INTO AYAH VALUES(248, 'الفتنة ', 217, 2);
INSERT INTO AYAH VALUES(249, 'حبطت ', 217, 2);
INSERT INTO AYAH VALUES(250, 'الميسر ', 219, 2);
INSERT INTO AYAH VALUES(251, 'العفو ', 219, 2);
INSERT INTO AYAH VALUES(252, 'لأعنَتكم ', 220, 2);
INSERT INTO AYAH VALUES(253, 'أذى ', 222, 2);
INSERT INTO AYAH VALUES(254, 'حرث لكم ', 223, 2);
INSERT INTO AYAH VALUES(255, 'أنّى شئتم ', 223, 2);
INSERT INTO AYAH VALUES(256, 'عرضة لأيمانكم ', 224, 2);
INSERT INTO AYAH VALUES(257, 'باللغو في أيمانكم ', 225, 2);
INSERT INTO AYAH VALUES(258, 'يؤلون من نسائهم ', 226, 2);
INSERT INTO AYAH VALUES(259, 'تربّص ', 226, 2);
INSERT INTO AYAH VALUES(260, 'فاءوا ', 226, 2);
INSERT INTO AYAH VALUES(261, 'ثلاث قروء ', 228, 2);
INSERT INTO AYAH VALUES(262, 'بعولتهن ', 228, 2);
INSERT INTO AYAH VALUES(263, 'درجة ', 228, 2);
INSERT INTO AYAH VALUES(264, 'الطلاق مرّتان ', 229, 2);
INSERT INTO AYAH VALUES(265, 'تسريح بإحسان ', 229, 2);
INSERT INTO AYAH VALUES(266, 'تلك حدود الله ', 229, 2);
INSERT INTO AYAH VALUES(267, 'فبلغن أجلهنّ', 231, 2);
INSERT INTO AYAH VALUES(268, 'و لا تمسكوهنّ ضرارا ', 231, 2);
INSERT INTO AYAH VALUES(269, 'آيات الله هزوا ', 231, 2);
INSERT INTO AYAH VALUES(270, 'الكتاب و الحكمة ', 231, 2);
INSERT INTO AYAH VALUES(271, 'فلا تعضلوهنّ', 232, 2);
INSERT INTO AYAH VALUES(272, 'أزكى لكم ', 232, 2);
INSERT INTO AYAH VALUES(273, 'وُسعها ', 233, 2);
INSERT INTO AYAH VALUES(274, 'و على الوارث', 233, 2);
INSERT INTO AYAH VALUES(275, 'أرادا فصلا ', 233, 2);
INSERT INTO AYAH VALUES(276, 'عرّضتم به ', 235, 2);
INSERT INTO AYAH VALUES(277, 'أكننتم ', 235, 2);
INSERT INTO AYAH VALUES(278, 'لا تواعدوهنّ سرّا ', 235, 2);
INSERT INTO AYAH VALUES(279, 'يبلغ الكتاب أجله ', 235, 2);
INSERT INTO AYAH VALUES(280, 'فريضة ', 236, 2);
INSERT INTO AYAH VALUES(281, 'متّعوهن ', 236, 2);
INSERT INTO AYAH VALUES(282, 'الموسع ', 236, 2);
INSERT INTO AYAH VALUES(283, 'قدره ', 236, 2);
INSERT INTO AYAH VALUES(284, 'المقتر ', 236, 2);
INSERT INTO AYAH VALUES(285, 'الصّلاة الوسطى ', 238, 2);
INSERT INTO AYAH VALUES(286, 'قانتين ', 238, 2);
INSERT INTO AYAH VALUES(287, 'فرجالا ', 239, 2);
INSERT INTO AYAH VALUES(288, 'للمطلقات متاع ', 241, 2);
INSERT INTO AYAH VALUES(289, 'قرضا حسنا ', 245, 2);
INSERT INTO AYAH VALUES(290, 'يقبض و يبسط', 245, 2);
INSERT INTO AYAH VALUES(291, 'الملإ', 246, 2);
INSERT INTO AYAH VALUES(292, 'عسيتم ', 246, 2);
INSERT INTO AYAH VALUES(293, 'أنّى يكون ؟', 247, 2);
INSERT INTO AYAH VALUES(294, 'زاده بسطة ', 247, 2);
INSERT INTO AYAH VALUES(295, 'يأتيكم التابوت ', 248, 2);
INSERT INTO AYAH VALUES(296, 'فيه سكينة ', 248, 2);
INSERT INTO AYAH VALUES(297, 'فصل طالوت ', 249, 2);
INSERT INTO AYAH VALUES(298, 'مُبتليكم ', 249, 2);
INSERT INTO AYAH VALUES(299, 'اغترف ', 249, 2);
INSERT INTO AYAH VALUES(300, 'لا طاقة لنا ', 249, 2);
INSERT INTO AYAH VALUES(301, 'فئة ', 249, 2);
INSERT INTO AYAH VALUES(302, 'برزوا ', 250, 2);
INSERT INTO AYAH VALUES(303, 'الحكمة ', 251, 2);
INSERT INTO AYAH VALUES(304, 'بروح القدس ', 253, 2);
INSERT INTO AYAH VALUES(305, 'لا خُلّة ', 254, 2);
INSERT INTO AYAH VALUES(306, 'الحيّ', 255, 2);
INSERT INTO AYAH VALUES(307, 'القيّوم ', 255, 2);
INSERT INTO AYAH VALUES(308, 'سِنةٌ', 255, 2);
INSERT INTO AYAH VALUES(309, 'لا يئوده ', 255, 2);
INSERT INTO AYAH VALUES(310, 'تبين الرّشد ', 256, 2);
INSERT INTO AYAH VALUES(311, 'من الغيّ', 256, 2);
INSERT INTO AYAH VALUES(312, 'بالطّاغوت ', 256, 2);
INSERT INTO AYAH VALUES(313, 'بالعروة الوُثقى ', 256, 2);
INSERT INTO AYAH VALUES(314, 'لا انفصام لها ', 256, 2);
INSERT INTO AYAH VALUES(315, 'الذي حاجّ إبراهيم ', 258, 2);
INSERT INTO AYAH VALUES(316, 'فبُهِتَ', 258, 2);
INSERT INTO AYAH VALUES(317, 'خاوية على عروشها ', 259, 2);
INSERT INTO AYAH VALUES(318, 'أنّى يحيي؟', 259, 2);
INSERT INTO AYAH VALUES(319, 'لم يتسنّه ', 259, 2);
INSERT INTO AYAH VALUES(320, 'ننشزها ', 259, 2);
INSERT INTO AYAH VALUES(321, 'فصرهنّ إليك', 260, 2);
INSERT INTO AYAH VALUES(322, 'منّا ', 262, 2);
INSERT INTO AYAH VALUES(323, 'أذى ', 262, 2);
INSERT INTO AYAH VALUES(324, 'رئاء النّاس ', 264, 2);
INSERT INTO AYAH VALUES(325, 'صفوان ', 264, 2);
INSERT INTO AYAH VALUES(326, 'وابل ', 264, 2);
INSERT INTO AYAH VALUES(327, 'صلدا ', 264, 2);
INSERT INTO AYAH VALUES(328, 'تثبيتا ', 265, 2);
INSERT INTO AYAH VALUES(329, 'جنّة بربوة ', 265, 2);
INSERT INTO AYAH VALUES(330, 'أُكُلها ', 265, 2);
INSERT INTO AYAH VALUES(331, 'فطلّ', 265, 2);
INSERT INTO AYAH VALUES(332, 'إعصار ', 266, 2);
INSERT INTO AYAH VALUES(333, 'فيه نار', 266, 2);
INSERT INTO AYAH VALUES(334, 'لا تيمّموا الخبيث ', 267, 2);
INSERT INTO AYAH VALUES(335, 'تُغمضوا فيه ', 267, 2);
INSERT INTO AYAH VALUES(336, 'أحصروا ', 273, 2);
INSERT INTO AYAH VALUES(337, 'ضربا ', 273, 2);
INSERT INTO AYAH VALUES(338, 'التعفّف', 273, 2);
INSERT INTO AYAH VALUES(339, 'بسيماهم ', 273, 2);
INSERT INTO AYAH VALUES(340, 'إلحافا ', 273, 2);
INSERT INTO AYAH VALUES(341, 'يتخبطه الشيطان ', 275, 2);
INSERT INTO AYAH VALUES(342, 'المسّ', 275, 2);
INSERT INTO AYAH VALUES(343, 'يمحق الله الرّبا ', 276, 2);
INSERT INTO AYAH VALUES(344, 'بربي الصّدقات ', 276, 2);
INSERT INTO AYAH VALUES(345, 'فأذنوا بحرب', 279, 2);
INSERT INTO AYAH VALUES(346, 'عسرة ', 280, 2);
INSERT INTO AYAH VALUES(347, 'فنظرة ', 280, 2);
INSERT INTO AYAH VALUES(348, 'و ليملل', 282, 2);
INSERT INTO AYAH VALUES(349, 'لا يبخس منه ', 282, 2);
INSERT INTO AYAH VALUES(350, 'أن يملّ هو ', 282, 2);
INSERT INTO AYAH VALUES(351, 'لا يأب ', 282, 2);
INSERT INTO AYAH VALUES(352, 'لا تسأموا ', 282, 2);
INSERT INTO AYAH VALUES(353, 'أقسط ', 282, 2);
INSERT INTO AYAH VALUES(354, 'أقوم للشهادة ', 282, 2);
INSERT INTO AYAH VALUES(355, 'أدنى ', 282, 2);
INSERT INTO AYAH VALUES(356, 'فسوق', 282, 2);
INSERT INTO AYAH VALUES(357, 'غفرانك ', 285, 2);
INSERT INTO AYAH VALUES(358, 'وُسعها ', 286, 2);
INSERT INTO AYAH VALUES(359, 'إصرا ', 286, 2);
INSERT INTO AYAH VALUES(360, 'لا طاقة لنا به ', 286, 2);

--TAFSIR DATA
INSERT INTO TAFSIR VALUES(null, 'القرآن العظيم' , 1, 1);
INSERT INTO TAFSIR VALUES(null, 'لاشك في أنه حقّ من عند الله' , 2, 1);
INSERT INTO TAFSIR VALUES(null, 'هادٍ من الضلالة' , 3, 1);
INSERT INTO TAFSIR VALUES(null, 'الذين تجنبوا المعاصي وأدّوا الفرائض فوقوا أنفسهم العذاب ' , 4, 1);
INSERT INTO TAFSIR VALUES(null, 'على رشاد ونور ويقين' , 5, 1);
INSERT INTO TAFSIR VALUES(null, 'طبع الله' , 6, 1);
INSERT INTO TAFSIR VALUES(null, 'غطاء وستر' , 7, 1);
INSERT INTO TAFSIR VALUES(null, 'يعملون عمل المخادع' , 8, 1);
INSERT INTO TAFSIR VALUES(null, 'شك ونفاق أو تكذيب وجَحْد' , 9, 1);
INSERT INTO TAFSIR VALUES(null, 'انصرفوا إليهم أو انفردوا معهم ' , 10, 1);
INSERT INTO TAFSIR VALUES(null, 'يزيدهم أو يمهلهم' , 11, 1);
INSERT INTO TAFSIR VALUES(null, 'مجاوزتهم الحدّ وغلوّهم في الكفر ' , 12, 1);
INSERT INTO TAFSIR VALUES(null, 'يعمَونَ عن الرُّشد أو يتحيّرون' , 13, 1);
INSERT INTO TAFSIR VALUES(null, 'حالُهُم العجيبة، أو صفتهم ' , 14, 1);
INSERT INTO TAFSIR VALUES(null, 'أوقدها ' , 15, 1);
INSERT INTO TAFSIR VALUES(null, 'خرسٌ عن النّطق بالحق' , 16, 1);
INSERT INTO TAFSIR VALUES(null, 'الصيّب المطر النازل أو السحاب' , 17, 1);
INSERT INTO TAFSIR VALUES(null, 'يستلِبُها أو يذهب بها بسرعة' , 18, 1);
INSERT INTO TAFSIR VALUES(null, 'وقفوا وثبتوا في أماكنهم متحيِّرين  ' , 19, 1);
INSERT INTO TAFSIR VALUES(null, 'بساطاً و وِطاءً للاستقرارِ عليها' , 20, 1);
INSERT INTO TAFSIR VALUES(null, 'سقفا مرفوعاً او كالقُبّةِ المضروبة' , 21, 1);
INSERT INTO TAFSIR VALUES(null, 'أمثالاً من الأوثانِ تعبدونها' , 22, 1);
INSERT INTO TAFSIR VALUES(null, 'أحضِروا آلهتَكُم أو نُصَراءَكم ' , 23, 1);
INSERT INTO TAFSIR VALUES(null, 'في اللون والمنظر لافي الطعم' , 24, 1);
INSERT INTO TAFSIR VALUES(null, 'قصد إلى خلقِها بإرادتهِ قصداً سويا بلا صارفٍ عنه' , 25, 1);
INSERT INTO TAFSIR VALUES(null, 'أتمهنَّ وقومهُنَّ وأحكمهنَّ' , 26, 1);
INSERT INTO TAFSIR VALUES(null, 'يُريقُها عدواناً وظلماً' , 27, 1);
INSERT INTO TAFSIR VALUES(null, 'نُنَزهكَ عن كل سوء مثنين عليكَ ' , 28, 1);
INSERT INTO TAFSIR VALUES(null, 'نمجدُك ونطهرُ ذكرك عمّا لا يليق بعظمتك ' , 29, 1);
INSERT INTO TAFSIR VALUES(null, 'اخضعوا له، أو سجود تحية وتعظيم' , 30, 1);
INSERT INTO TAFSIR VALUES(null, 'أكلاً واسعاً أو هنيئاً لاعناء فيه' , 31, 1);
INSERT INTO TAFSIR VALUES(null, 'أذهَبَهُما وأبعَدَهُما ' , 32, 1);
INSERT INTO TAFSIR VALUES(null, 'لقبُ يعقوب عليه السلام' , 33, 1);
INSERT INTO TAFSIR VALUES(null, 'فخافونِ في نقضِكم العهد ' , 34, 1);
INSERT INTO TAFSIR VALUES(null, 'لاتخلِطوا ، أو لا تستُرُوا' , 35, 1);
INSERT INTO TAFSIR VALUES(null, 'بالتوسع في الخير والطاعات' , 36, 1);
INSERT INTO TAFSIR VALUES(null, 'لشاقّة ثقيلة صعبة' , 37, 1);
INSERT INTO TAFSIR VALUES(null, 'المتواضعين المُستكينين' , 38, 1);
INSERT INTO TAFSIR VALUES(null, 'يعلمون ويستيقنون' , 39, 1);
INSERT INTO TAFSIR VALUES(null, 'عالمي زمانكم ' , 40, 1);
INSERT INTO TAFSIR VALUES(null, 'لاتقضي ولاتؤدي نفسٌ' , 41, 1);
INSERT INTO TAFSIR VALUES(null, 'فدية' , 42, 1);
INSERT INTO TAFSIR VALUES(null, 'يكلِّفونكم ويذيقونكم ' , 43, 1);
INSERT INTO TAFSIR VALUES(null, 'يستَبقون بناتكم للخدمة' , 44, 1);
INSERT INTO TAFSIR VALUES(null, 'اختبار وامتحان بالنعم والنقمِ' , 45, 1);
INSERT INTO TAFSIR VALUES(null, 'فصلنا وشققنا ' , 46, 1);
INSERT INTO TAFSIR VALUES(null, 'جعلتموه إلهاً معبوداً' , 47, 1);
INSERT INTO TAFSIR VALUES(null, 'الشرع الفارقَ بين الحلال والحرام' , 48, 1);
INSERT INTO TAFSIR VALUES(null, 'مبدعكم ومحدثكم' , 49, 1);
INSERT INTO TAFSIR VALUES(null, 'فليقتل البريء منكم المجرم' , 50, 1);
INSERT INTO TAFSIR VALUES(null, 'عيانا بالبصر' , 51, 1);
INSERT INTO TAFSIR VALUES(null, 'نارٌ من السماء أو صيحةٌ منها ' , 52, 1);
INSERT INTO TAFSIR VALUES(null, 'السحاب الأبيض الرقيق' , 53, 1);
INSERT INTO TAFSIR VALUES(null, 'مادة صمغية حلوة كالعسل' , 54, 1);
INSERT INTO TAFSIR VALUES(null, 'الطائر المعروف بالسّماني ' , 55, 1);
INSERT INTO TAFSIR VALUES(null, 'أكلاً واسعاً أو هنيئاً لاعناءَ فيه' , 56, 1);
INSERT INTO TAFSIR VALUES(null, 'قولوا مسألتنا يا ربنا أن تحط عنا خطايانا' , 57, 1);
INSERT INTO TAFSIR VALUES(null, 'عذابًا ، قيل هو الطاعون ' , 58, 1);
INSERT INTO TAFSIR VALUES(null, 'فانشقت و سالت بكثرة ' , 59, 1);
INSERT INTO TAFSIR VALUES(null, 'موضع شربهم ' , 60, 1);
INSERT INTO TAFSIR VALUES(null, 'لا تفسدوا فيها ' , 61, 1);
INSERT INTO TAFSIR VALUES(null, 'متمادين في الفساد ' , 62, 1);
INSERT INTO TAFSIR VALUES(null, 'الحنطة ، أو الثوم ' , 63, 1);
INSERT INTO TAFSIR VALUES(null, 'أحاطت بهم أو ألصقت بهم ' , 64, 1);
INSERT INTO TAFSIR VALUES(null, 'الذلّ و الصّغار و الهوان ' , 65, 1);
INSERT INTO TAFSIR VALUES(null, 'فقر النفس و شحّها ' , 66, 1);
INSERT INTO TAFSIR VALUES(null, ' رجعوا به مستحقين له ' , 67, 1);
INSERT INTO TAFSIR VALUES(null, 'صاروا يهودا ' , 68, 1);
INSERT INTO TAFSIR VALUES(null, 'عبدة الملائكة أو الكواكب' , 69, 1);
INSERT INTO TAFSIR VALUES(null, 'العهد عليكم بالعمل بما في التوراة ' , 70, 1);
INSERT INTO TAFSIR VALUES(null, 'مُبعدين مطرودين صاغرين' , 71, 1);
INSERT INTO TAFSIR VALUES(null, 'عقوبة  ' , 72, 1);
INSERT INTO TAFSIR VALUES(null, 'سخرية ' , 73, 1);
INSERT INTO TAFSIR VALUES(null, 'لا مسنّة و لا فتيّة ' , 74, 1);
INSERT INTO TAFSIR VALUES(null, 'نَصَف (وسط ) بين السنّين ' , 75, 1);
INSERT INTO TAFSIR VALUES(null, 'شديد الصّفرة ' , 76, 1);
INSERT INTO TAFSIR VALUES(null, 'ليست هيّنة سهلة الإنقياد' , 77, 1);
INSERT INTO TAFSIR VALUES(null, 'تقلب الأرض للزّراعة ' , 78, 1);
INSERT INTO TAFSIR VALUES(null, 'الزّرع أو الأرض المهيّأة له ' , 79, 1);
INSERT INTO TAFSIR VALUES(null, 'مبرّأة من العيوب' , 80, 1);
INSERT INTO TAFSIR VALUES(null, 'لا لون فيها غير الصّفرة الفاقعة ' , 81, 1);
INSERT INTO TAFSIR VALUES(null, 'فتدافعتم و تخاصمتم فيها ' , 82, 1);
INSERT INTO TAFSIR VALUES(null, 'بتفتّح بسعة و كثرة ' , 83, 1);
INSERT INTO TAFSIR VALUES(null, 'يتصدّع بطول أو بعرض' , 84, 1);
INSERT INTO TAFSIR VALUES(null, 'يبدّلونه ، أو يؤوّلون بالباطل ' , 85, 1);
INSERT INTO TAFSIR VALUES(null, 'مضى إليه ، أو انفرد معه ' , 86, 1);
INSERT INTO TAFSIR VALUES(null, 'حكم به أو قصّه عليكم ' , 87, 1);
INSERT INTO TAFSIR VALUES(null, 'جهلة بكتابهم (التوراة)' , 88, 1);
INSERT INTO TAFSIR VALUES(null, 'أكاذيب تلقّوها عن أحبارهم ' , 89, 1);
INSERT INTO TAFSIR VALUES(null, 'هلكة أو حسرة أو شدّة عذاب أو وادٍ عميق في جهنّم ' , 90, 1);
INSERT INTO TAFSIR VALUES(null, 'هي هنا الكفر' , 91, 1);
INSERT INTO TAFSIR VALUES(null, 'أحدقت به و استولت عليه ' , 92, 1);
INSERT INTO TAFSIR VALUES(null, 'تتعاونون عليهم ' , 93, 1);
INSERT INTO TAFSIR VALUES(null, 'مأسورين ' , 94, 1);
INSERT INTO TAFSIR VALUES(null, 'تخرجوهم من الأسر بإعطاء الفدية ' , 95, 1);
INSERT INTO TAFSIR VALUES(null, 'هوان و فضيحة و عقوبة ' , 96, 1);
INSERT INTO TAFSIR VALUES(null, 'أتبعنا على أثره الرّسل على منهاجه يحكمون بشريعته' , 97, 1);
INSERT INTO TAFSIR VALUES(null, 'بالروح المطهّر جبريل عليه السلام ' , 98, 1);
INSERT INTO TAFSIR VALUES(null, 'عليها أغشية و أغطية خِلقيّة ' , 99, 1);
INSERT INTO TAFSIR VALUES(null, 'يستنصرون ببعثه صلى الله عليه و سلم' , 100, 1);
INSERT INTO TAFSIR VALUES(null, 'باعوا به أنفسهم  ' , 101, 1);
INSERT INTO TAFSIR VALUES(null, 'حسدا ' , 102, 1);
INSERT INTO TAFSIR VALUES(null, 'فرجعوا به مُسْتحِقّين له ' , 103, 1);
INSERT INTO TAFSIR VALUES(null, 'جعلتموه إلها معبودًا .' , 104, 1);
INSERT INTO TAFSIR VALUES(null, 'حبّ العِجل الذي عبدوه ' , 105, 1);
INSERT INTO TAFSIR VALUES(null, 'لو يطول عُمُرُه ' , 106, 1);
INSERT INTO TAFSIR VALUES(null, 'طرحه و نقضه ' , 107, 1);
INSERT INTO TAFSIR VALUES(null, 'تقرأ  أو تكذِب من السِّحر' , 108, 1);
INSERT INTO TAFSIR VALUES(null, 'ابتلاء و اختبار من الله تعالى ' , 109, 1);
INSERT INTO TAFSIR VALUES(null, 'نصيب من الخير ، أو قدْر ٍ' , 110, 1);
INSERT INTO TAFSIR VALUES(null, 'باعوا به أنفسهم ' , 111, 1);
INSERT INTO TAFSIR VALUES(null, 'كلمة سبّ و تنقيصٍٍ عند اليهود' , 112, 1);
INSERT INTO TAFSIR VALUES(null, 'انظر إلينا أو انتظرنا و تأنّ علينا ' , 113, 1);
INSERT INTO TAFSIR VALUES(null, 'ما نُزِلَ و نرفعْ من حُكمِ آيةٍ أو التّعبّد بها ' , 114, 1);
INSERT INTO TAFSIR VALUES(null, 'نمحها من القلوب و الحوافظ' , 115, 1);
INSERT INTO TAFSIR VALUES(null, 'مالك أو متولّ لأموركم ' , 116, 1);
INSERT INTO TAFSIR VALUES(null, 'قصد الطريق و وسطه ' , 117, 1);
INSERT INTO TAFSIR VALUES(null, 'شهواتهم و مُتمنّياتهم الباطلة ' , 118, 1);
INSERT INTO TAFSIR VALUES(null, 'أخلص نفسه أو قصده أو عبادته لله ' , 119, 1);
INSERT INTO TAFSIR VALUES(null, 'ذلّ و صغار ، و قتل و أسرٌ' , 120, 1);
INSERT INTO TAFSIR VALUES(null, 'جِهتُهُ  التي رضيها و أمركم بها ' , 121, 1);
INSERT INTO TAFSIR VALUES(null, 'تنزيها له تعالى عن اتّخاذ الولد ' , 122, 1);
INSERT INTO TAFSIR VALUES(null, 'مُطيعون مُنقادون له تعالى ' , 123, 1);
INSERT INTO TAFSIR VALUES(null, 'مُبتدع و مُخترع ..' , 124, 1);
INSERT INTO TAFSIR VALUES(null, 'أراد شيئا أو أحكمه أو حتّمه ' , 125, 1);
INSERT INTO TAFSIR VALUES(null, 'احْدُثُ ، فهو يحدُثُ ' , 126, 1);
INSERT INTO TAFSIR VALUES(null, 'عالمي زمانكم' , 127, 1);
INSERT INTO TAFSIR VALUES(null, 'لا تقضي و لا تؤدّي نفس ' , 128, 1);
INSERT INTO TAFSIR VALUES(null, 'فِدْية ' , 129, 1);
INSERT INTO TAFSIR VALUES(null, 'اختبر و امتحن' , 130, 1);
INSERT INTO TAFSIR VALUES(null, 'بأوامرَ و نواهٍ' , 131, 1);
INSERT INTO TAFSIR VALUES(null, 'أدّاهُنّ لله تعالى على كمال ' , 132, 1);
INSERT INTO TAFSIR VALUES(null, 'مَرْجِعًا أو ملجأ أو مَجْمَعًا أو موضع ثواب لهم ' , 133, 1);
INSERT INTO TAFSIR VALUES(null, 'وصّينا أو أمرنا أو أوحينا . .' , 134, 1);
INSERT INTO TAFSIR VALUES(null, 'الكعبة المشرّفة بمكة المكرّمة ' , 135, 1);
INSERT INTO TAFSIR VALUES(null, 'أدفعه و أسوقه و ألجئه ' , 136, 1);
INSERT INTO TAFSIR VALUES(null, 'منقادين خاضعين مُخلصين لك' , 137, 1);
INSERT INTO TAFSIR VALUES(null, 'عرِّفنا معالم حجِّنا  أو شرائعه' , 138, 1);
INSERT INTO TAFSIR VALUES(null, 'يطهّرهم من الشّرك و المعاصي' , 139, 1);
INSERT INTO TAFSIR VALUES(null, 'يزهد و ينصرف عن . .   ' , 140, 1);
INSERT INTO TAFSIR VALUES(null, 'جهِلها أو امتهنها و استخفّ بها ، أو أهلكها ' , 141, 1);
INSERT INTO TAFSIR VALUES(null, 'انْقَدْ أو أخلِص العبادة لي ' , 142, 1);
INSERT INTO TAFSIR VALUES(null, 'دين الإسلام صفوة الأديان ' , 143, 1);
INSERT INTO TAFSIR VALUES(null, 'مضت و سلفت ' , 144, 1);
INSERT INTO TAFSIR VALUES(null, 'مائلا عن الباطل إلى الدّين الحقّ' , 145, 1);
INSERT INTO TAFSIR VALUES(null, 'أولاد يعقوب أو أحفاده' , 146, 1);
INSERT INTO TAFSIR VALUES(null, 'الزموا دين الله ، أو فطرة الله ' , 147, 1);
INSERT INTO TAFSIR VALUES(null, 'الخفاف العقول  اليهود و من شاكلهم في إنكار تحويل القبلة ' , 148, 1);
INSERT INTO TAFSIR VALUES(null, 'أيّ شيء صرفهم ' , 149, 1);
INSERT INTO TAFSIR VALUES(null, 'عن بيت المقدس' , 150, 1);
INSERT INTO TAFSIR VALUES(null, 'خيارا أو متوسّطين مُعتدلين' , 151, 1);
INSERT INTO TAFSIR VALUES(null, 'يرتدّ عن الإسلام عند تحويل القبلة إلى الكعبة ' , 152, 1);
INSERT INTO TAFSIR VALUES(null, 'لشاقّة ثقيلة على النّفوس ' , 153, 1);
INSERT INTO TAFSIR VALUES(null, 'صلاتكم إلى بيت المقدس ' , 154, 1);
INSERT INTO TAFSIR VALUES(null, 'تلقاء الكعبة ' , 155, 1);
INSERT INTO TAFSIR VALUES(null, 'الشّاكّين في كتمانهم الحقّ مع العلم به ' , 156, 1);
INSERT INTO TAFSIR VALUES(null, 'يُطهّرهم من الشّرك و المعاصي ' , 157, 1);
INSERT INTO TAFSIR VALUES(null, 'القرآن و السّنن و الفقه في الدّين' , 158, 1);
INSERT INTO TAFSIR VALUES(null, 'لنختبرنّكم و نحن أعلم بأموركم ' , 159, 1);
INSERT INTO TAFSIR VALUES(null, 'ثناءٌ أو مغفرة منه تعالى ' , 160, 1);
INSERT INTO TAFSIR VALUES(null, 'معالم دينه في الحجّ و العمرة ' , 161, 1);
INSERT INTO TAFSIR VALUES(null, 'زار البيت المعظّم على الوجه المشروع' , 162, 1);
INSERT INTO TAFSIR VALUES(null, 'فلا إثم عليه ' , 163, 1);
INSERT INTO TAFSIR VALUES(null, 'يدور بهما و يسعى بينهما ' , 164, 1);
INSERT INTO TAFSIR VALUES(null, 'يطردهم من رحمته' , 165, 1);
INSERT INTO TAFSIR VALUES(null, 'يؤخّرون عن العذاب لحظة' , 166, 1);
INSERT INTO TAFSIR VALUES(null, 'فرّق و نشر فيها بالتّوالد' , 167, 1);
INSERT INTO TAFSIR VALUES(null, 'تقليبها في مهابِّها و أحوالها ' , 168, 1);
INSERT INTO TAFSIR VALUES(null, 'أمثالا من الأوثان يعبدونها' , 169, 1);
INSERT INTO TAFSIR VALUES(null, 'نفرّقت الصّلات التي كانت بينهم في الدّنيا من نسب و صداقة و عهود' , 170, 1);
INSERT INTO TAFSIR VALUES(null, 'عودة إلى الدّنيا ' , 171, 1);
INSERT INTO TAFSIR VALUES(null, 'ندامات شديدة ' , 172, 1);
INSERT INTO TAFSIR VALUES(null, 'طُرُقُه و آثارُه  و أعماله' , 173, 1);
INSERT INTO TAFSIR VALUES(null, 'بالمعاصي و الذنوب' , 174, 1);
INSERT INTO TAFSIR VALUES(null, 'ما عظُم قُبْحُه من الذّنوب' , 175, 1);
INSERT INTO TAFSIR VALUES(null, 'وجدنا' , 176, 1);
INSERT INTO TAFSIR VALUES(null, 'يُصوّت و يصيح' , 177, 1);
INSERT INTO TAFSIR VALUES(null, 'خرسٌ عن النّطق بالحقّ' , 178, 1);
INSERT INTO TAFSIR VALUES(null, 'المسفوح و هو السّائل ' , 179, 1);
INSERT INTO TAFSIR VALUES(null, 'يعني الخنزير بجميع أجزائه ' , 180, 1);
INSERT INTO TAFSIR VALUES(null, 'ما ذُكر عند ذبحه اسم غيره تعالى من الأصنام و غيرها ' , 181, 1);
INSERT INTO TAFSIR VALUES(null, 'ألجأته الضّرورة إلى التناول ممّا حرّم' , 182, 1);
INSERT INTO TAFSIR VALUES(null, 'غير طالب للمحرّم للذّة أو استئثار على مضطرّ آخر ' , 183, 1);
INSERT INTO TAFSIR VALUES(null, 'و لا مُتجاوز ما يسدّ الرّمق' , 184, 1);
INSERT INTO TAFSIR VALUES(null, 'عِوضا يسيرا' , 185, 1);
INSERT INTO TAFSIR VALUES(null, 'لا يُطهّرهم من دنس ذنوبهم' , 186, 1);
INSERT INTO TAFSIR VALUES(null, 'خلاف و نزاع بعيد عن الحقّ' , 187, 1);
INSERT INTO TAFSIR VALUES(null, 'هو التوسّع في الطاعات و أعمال الخير ' , 188, 1);
INSERT INTO TAFSIR VALUES(null, 'المسافر الّذي انقطع عن أهله ' , 189, 1);
INSERT INTO TAFSIR VALUES(null, 'في تحريرها من الرّق أو الأسر' , 190, 1);
INSERT INTO TAFSIR VALUES(null, 'أخصّ الصّابرين لمزيد فضلهم' , 191, 1);
INSERT INTO TAFSIR VALUES(null, 'البؤس و الفقر و السّقم و الألم  ' , 192, 1);
INSERT INTO TAFSIR VALUES(null, 'وقت قتال العدو ' , 193, 1);
INSERT INTO TAFSIR VALUES(null, 'فُرض عليكم ' , 194, 1);
INSERT INTO TAFSIR VALUES(null, 'تُرك له من وليّ المقتول' , 195, 1);
INSERT INTO TAFSIR VALUES(null, 'خلّف مالا كثيرا ' , 196, 1);
INSERT INTO TAFSIR VALUES(null, 'نُسخ وجوبها بآية المواريث' , 197, 1);
INSERT INTO TAFSIR VALUES(null, 'ميلا عن الحقّ خطأ ً و جهلاً' , 198, 1);
INSERT INTO TAFSIR VALUES(null, 'ارتكابا للظّلم عمدًا ' , 199, 1);
INSERT INTO TAFSIR VALUES(null, 'يستطيعونه ، و الحكم منسوخ بآية "فمن شَهِد"' , 200, 1);
INSERT INTO TAFSIR VALUES(null, 'زاد في الفدية ' , 201, 1);
INSERT INTO TAFSIR VALUES(null, 'لتحمدوا الله و تُثنوا عليه ' , 202, 1);
INSERT INTO TAFSIR VALUES(null, 'الِوقاع' , 203, 1);
INSERT INTO TAFSIR VALUES(null, ' سكنٌ أو سترٌ لكم عن الحرام ' , 204, 1);
INSERT INTO TAFSIR VALUES(null, 'منهيّاته و محرّماته' , 205, 1);
INSERT INTO TAFSIR VALUES(null, 'تُلقوا بالخصومة فيها ظلما و باطلا ' , 206, 1);
INSERT INTO TAFSIR VALUES(null, 'وجدّتموهم و أدركتموهم ' , 207, 1);
INSERT INTO TAFSIR VALUES(null, 'الشّرك بالله و هو في الحَرَم' , 208, 1);
INSERT INTO TAFSIR VALUES(null, 'في الحَرَم كلّه' , 209, 1);
INSERT INTO TAFSIR VALUES(null, 'ما تجب المحافظة عليه ' , 210, 1);
INSERT INTO TAFSIR VALUES(null, 'الهلاك بترك الجهاد و الإنفاق فيه ' , 211, 1);
INSERT INTO TAFSIR VALUES(null, 'مُنِعتم عن الإتمام بعد الإحرام ' , 212, 1);
INSERT INTO TAFSIR VALUES(null, 'فعليكم  ما تيسّر و تسهّل' , 213, 1);
INSERT INTO TAFSIR VALUES(null, 'ممّا يُهدى إلى البيت من الأنعام ' , 214, 1);
INSERT INTO TAFSIR VALUES(null, 'لا تحلّوا من الإحرام بالحلق ' , 215, 1);
INSERT INTO TAFSIR VALUES(null, 'مكان وجوب ذبحه (الحرم) أو حيث أحصِرتم (حِلاً أو حَرَمًا)' , 216, 1);
INSERT INTO TAFSIR VALUES(null, ' فعليه إذا حلق فدية ' , 217, 1);
INSERT INTO TAFSIR VALUES(null, 'ذبيحة ، و المراد هنا شاة ' , 218, 1);
INSERT INTO TAFSIR VALUES(null, 'هو هدي التّمتّع' , 219, 1);
INSERT INTO TAFSIR VALUES(null, 'ألزم نفسه بالإحرام ' , 220, 1);
INSERT INTO TAFSIR VALUES(null, 'فلا وقاع ، أو فلا إفحاش في القول' , 221, 1);
INSERT INTO TAFSIR VALUES(null, 'لا خصام و لا مماراة و لا ملاحاةٌ فيه ' , 222, 1);
INSERT INTO TAFSIR VALUES(null, 'إثم و حرج' , 223, 1);
INSERT INTO TAFSIR VALUES(null, 'رزق بالتجارة و الإكتساب في الحجّ' , 224, 1);
INSERT INTO TAFSIR VALUES(null, 'دفعتم أنفسكم بكثرة و سِرتم ' , 225, 1);
INSERT INTO TAFSIR VALUES(null, 'مُزدلفة كلّها أو جبل قُزح ' , 226, 1);
INSERT INTO TAFSIR VALUES(null, 'عباداتكم الحجّيّة' , 227, 1);
INSERT INTO TAFSIR VALUES(null, 'نصيب من الخير أو قدر' , 228, 1);
INSERT INTO TAFSIR VALUES(null, 'النّعمة و العافية و التوفيق ' , 229, 1);
INSERT INTO TAFSIR VALUES(null, 'الرّحمة و الإحسان و النّجاة ' , 230, 1);
INSERT INTO TAFSIR VALUES(null, 'شديد المخاصمة في الباطل ' , 231, 1);
INSERT INTO TAFSIR VALUES(null, 'الزّرع ' , 232, 1);
INSERT INTO TAFSIR VALUES(null, 'حملته الأنفة و الحميّة عليه ' , 233, 1);
INSERT INTO TAFSIR VALUES(null, 'كافيه جزاءً نار جهنّم ' , 234, 1);
INSERT INTO TAFSIR VALUES(null, 'لبئس الفراش و المضجع جهنّم ' , 235, 1);
INSERT INTO TAFSIR VALUES(null, 'يبيعها ببذلها في طاعة الله ' , 236, 1);
INSERT INTO TAFSIR VALUES(null, 'في الإسلام و شرائعه كلّها ' , 237, 1);
INSERT INTO TAFSIR VALUES(null, 'طُرقه و آثاره و أعماله' , 238, 1);
INSERT INTO TAFSIR VALUES(null, 'ملتُم و ضللتم عن الحقّ' , 239, 1);
INSERT INTO TAFSIR VALUES(null, 'طاقات من السّحاب الأبيض الرقيق ' , 240, 1);
INSERT INTO TAFSIR VALUES(null, 'بلا نهاية  لما يُعطيه ، أو بلا تقتير ' , 241, 1);
INSERT INTO TAFSIR VALUES(null, 'حسدا بينهم و ظلما لتكالبهم على الدّنيا ' , 242, 1);
INSERT INTO TAFSIR VALUES(null, 'حال الذين مضوا من المؤمنين' , 243, 1);
INSERT INTO TAFSIR VALUES(null, 'البؤس و الفقر ، و السقم و الألم ' , 244, 1);
INSERT INTO TAFSIR VALUES(null, 'أُزعِجوا إزعاجا شديدا بالبلايا ' , 245, 1);
INSERT INTO TAFSIR VALUES(null, 'مكروه لكم طبعا ' , 246, 1);
INSERT INTO TAFSIR VALUES(null, 'مُسْتكْبر عظيم وزرًا ' , 247, 1);
INSERT INTO TAFSIR VALUES(null, 'الشّرك و الكفر بالله تعالى ' , 248, 1);
INSERT INTO TAFSIR VALUES(null, 'فسدت و بطلت ' , 249, 1);
INSERT INTO TAFSIR VALUES(null, 'القمار ' , 250, 1);
INSERT INTO TAFSIR VALUES(null, 'ما فضل عن قدر الحاجة ' , 251, 1);
INSERT INTO TAFSIR VALUES(null, 'لكلّفكم ما يشقّ عليكم ' , 252, 1);
INSERT INTO TAFSIR VALUES(null, 'قذر يُؤذي ' , 253, 1);
INSERT INTO TAFSIR VALUES(null, 'مزرع الذرية لكم ' , 254, 1);
INSERT INTO TAFSIR VALUES(null, 'كيف شئتم ما دام في القُبُل ' , 255, 1);
INSERT INTO TAFSIR VALUES(null, 'مانعا عن الخير لحلفكم به على تركه' , 256, 1);
INSERT INTO TAFSIR VALUES(null, 'هو أن يحلف على الشيء مُعتقدا صدقه و الأمر بخلافه ، أو ما يجري على اللّسان ممّا لا يُقصد به اليمين ' , 257, 1);
INSERT INTO TAFSIR VALUES(null, 'يحلفون على ترك مواقعة زوجاتهم ' , 258, 1);
INSERT INTO TAFSIR VALUES(null, 'انتظار ' , 259, 1);
INSERT INTO TAFSIR VALUES(null, 'رجعوا في المدّة عمّا حلفوا عليه ' , 260, 1);
INSERT INTO TAFSIR VALUES(null, 'حيض ، وقيل أطهار ' , 261, 1);
INSERT INTO TAFSIR VALUES(null, 'أزواجهن ' , 262, 1);
INSERT INTO TAFSIR VALUES(null, 'منزلة و فضيلة بالرعاية و الإنفاق' , 263, 1);
INSERT INTO TAFSIR VALUES(null, 'التطليق الرّجعي مرّة بعد مرّة ' , 264, 1);
INSERT INTO TAFSIR VALUES(null, 'طلاق مع أداء الحقوق و عدم المصارّة ' , 265, 1);
INSERT INTO TAFSIR VALUES(null, 'أحكامه المفروضة ' , 266, 1);
INSERT INTO TAFSIR VALUES(null, 'شارفن انقضاء عدّتهنّ' , 267, 1);
INSERT INTO TAFSIR VALUES(null, 'مضارّة لهنّ' , 268, 1);
INSERT INTO TAFSIR VALUES(null, 'سخريّة بالتّهاون في المحافظة عليها ' , 269, 1);
INSERT INTO TAFSIR VALUES(null, 'القرآن و السّنّة ' , 270, 1);
INSERT INTO TAFSIR VALUES(null, 'فلا تمنعوهنّ' , 271, 1);
INSERT INTO TAFSIR VALUES(null, 'أنمى و أنفع لكم ' , 272, 1);
INSERT INTO TAFSIR VALUES(null, 'طاقتها و قدر إمكانها ' , 273, 1);
INSERT INTO TAFSIR VALUES(null, 'وارث الولد عند عدم الأب ' , 274, 1);
INSERT INTO TAFSIR VALUES(null, 'فطاما للولد قبل الحولين ' , 275, 1);
INSERT INTO TAFSIR VALUES(null, 'لوّحتم و أشرتم به ' , 276, 1);
INSERT INTO TAFSIR VALUES(null, 'أسررتم و أخفيتم ' , 277, 1);
INSERT INTO TAFSIR VALUES(null, 'لا تذكروا لهنّ صريح النّكاح' , 278, 1);
INSERT INTO TAFSIR VALUES(null, 'ينتهي المفروض من العدّة ' , 279, 1);
INSERT INTO TAFSIR VALUES(null, 'مهرا' , 280, 1);
INSERT INTO TAFSIR VALUES(null, 'أعطوهنّ ما يتمتّعن به ' , 281, 1);
INSERT INTO TAFSIR VALUES(null, 'ذي السّعة و الغنى ' , 282, 1);
INSERT INTO TAFSIR VALUES(null, 'قدر إمكانه و طاقته ' , 283, 1);
INSERT INTO TAFSIR VALUES(null, 'الفقير الضيّق الحال ' , 284, 1);
INSERT INTO TAFSIR VALUES(null, 'صلاة العصر لمزيد فضلها ' , 285, 1);
INSERT INTO TAFSIR VALUES(null, 'مطيعين خاشعين ' , 286, 1);
INSERT INTO TAFSIR VALUES(null, 'فصلّوا مُشاةً على أرجلكم ' , 287, 1);
INSERT INTO TAFSIR VALUES(null, 'متعة أو نفقة العدّة ' , 288, 1);
INSERT INTO TAFSIR VALUES(null, 'احتسابا به عن طيبة نفس ' , 289, 1);
INSERT INTO TAFSIR VALUES(null, 'يضيّق على بعض و يوسّع على آخرين ' , 290, 1);
INSERT INTO TAFSIR VALUES(null, 'وجوه القوم و كُبرائهم ' , 291, 1);
INSERT INTO TAFSIR VALUES(null, 'قاربتم ' , 292, 1);
INSERT INTO TAFSIR VALUES(null, 'كيف أو من أين يكون ؟' , 293, 1);
INSERT INTO TAFSIR VALUES(null, 'سعة و امتدادا و فضيلة ' , 294, 1);
INSERT INTO TAFSIR VALUES(null, 'صندوق التوراة ' , 295, 1);
INSERT INTO TAFSIR VALUES(null, 'سكون و طمأنينة لقلوبكم ' , 296, 1);
INSERT INTO TAFSIR VALUES(null, 'انفصل عن بين المقدس ' , 297, 1);
INSERT INTO TAFSIR VALUES(null, 'مختبركم و هو أعلم بأمركم ' , 298, 1);
INSERT INTO TAFSIR VALUES(null, 'أخذ بيده دون الكرْع ' , 299, 1);
INSERT INTO TAFSIR VALUES(null, 'لا قدرة و لا قوّة لنا' , 300, 1);
INSERT INTO TAFSIR VALUES(null, 'جماعة من النّاس ' , 301, 1);
INSERT INTO TAFSIR VALUES(null, 'ظهروا و انكشفوا' , 302, 1);
INSERT INTO TAFSIR VALUES(null, 'النبوّة  ' , 303, 1);
INSERT INTO TAFSIR VALUES(null, 'جبريل عليه السلام ' , 304, 1);
INSERT INTO TAFSIR VALUES(null, 'لا موّدة و لا صداقة ' , 305, 1);
INSERT INTO TAFSIR VALUES(null, 'الدائم الحياة بلا زوال ' , 306, 1);
INSERT INTO TAFSIR VALUES(null, 'الدائم القيام بتدبير الخلق و حفظهم ' , 307, 1);
INSERT INTO TAFSIR VALUES(null, 'نعاس و غفوة ' , 308, 1);
INSERT INTO TAFSIR VALUES(null, 'لا يُثقله ، و لا يشق عليه ' , 309, 1);
INSERT INTO TAFSIR VALUES(null, 'تميّز الهدى و الإيمان ' , 310, 1);
INSERT INTO TAFSIR VALUES(null, 'من الضّلالة و الكفر' , 311, 1);
INSERT INTO TAFSIR VALUES(null, 'ما يُطغي من صنم و شيطان و نحوهما ' , 312, 1);
INSERT INTO TAFSIR VALUES(null, 'بالعقيدة المُحكة الوثيقة ' , 313, 1);
INSERT INTO TAFSIR VALUES(null, 'لا انقطاع و لا زوال لها ' , 314, 1);
INSERT INTO TAFSIR VALUES(null, 'هم نمرود بن كنعان الجبّار' , 315, 1);
INSERT INTO TAFSIR VALUES(null, 'غُلِب و تحيّر و انقطعت حُجّته' , 316, 1);
INSERT INTO TAFSIR VALUES(null, 'ساقطة على سقوفها التي سقطت ' , 317, 1);
INSERT INTO TAFSIR VALUES(null, 'كيف أو متى يُحيي؟ ' , 318, 1);
INSERT INTO TAFSIR VALUES(null, 'لم يتغيّر مع مرور السّنين عليه ' , 319, 1);
INSERT INTO TAFSIR VALUES(null, 'نرفعها من الأرض لنؤلّفها ' , 320, 1);
INSERT INTO TAFSIR VALUES(null, 'أمِلهنّ  أو قطّعهنّ مَمَالةً إليك ' , 321, 1);
INSERT INTO TAFSIR VALUES(null, 'عدّا للإحسانا و اظهارا له ' , 322, 1);
INSERT INTO TAFSIR VALUES(null, 'تطاولا و تفاخرا بالانفاق أو تبرُّما منه ' , 323, 1);
INSERT INTO TAFSIR VALUES(null, 'مُراءة لهم و سُمعة لا لوجهه تعالى ' , 324, 1);
INSERT INTO TAFSIR VALUES(null, 'حجر كبير أملس ' , 325, 1);
INSERT INTO TAFSIR VALUES(null, 'مطر شديد عظيم القطر ' , 326, 1);
INSERT INTO TAFSIR VALUES(null, 'أجردَ نقيّا من التراب' , 327, 1);
INSERT INTO TAFSIR VALUES(null, 'تصديقا و يقينا بثواب الإنفاق ' , 328, 1);
INSERT INTO TAFSIR VALUES(null, 'بستان بمرتفع من الأرض ' , 329, 1);
INSERT INTO TAFSIR VALUES(null, 'ثمرها الذي يؤكل ' , 330, 1);
INSERT INTO TAFSIR VALUES(null, 'فمطر خفيف (رذاذ)' , 331, 1);
INSERT INTO TAFSIR VALUES(null, 'ريح عاصف (زوبعة)' , 332, 1);
INSERT INTO TAFSIR VALUES(null, 'سموم شديد أو صاعقة ' , 333, 1);
INSERT INTO TAFSIR VALUES(null, 'لا تقصدوا المال الرّديء' , 334, 1);
INSERT INTO TAFSIR VALUES(null, 'تتساهلوا و تتسامحوا في أخذه ' , 335, 1);
INSERT INTO TAFSIR VALUES(null, 'حبسهم الجهاد عن التصرف ' , 336, 1);
INSERT INTO TAFSIR VALUES(null, 'ذهابا و سيرا للتكسّب ' , 337, 1);
INSERT INTO TAFSIR VALUES(null, 'التّنزّه عن السؤال ' , 338, 1);
INSERT INTO TAFSIR VALUES(null, 'بهيأتهم الدالّة على الفاقة و الحاجة ' , 339, 1);
INSERT INTO TAFSIR VALUES(null, 'إحاحا في يالسّؤال ' , 340, 1);
INSERT INTO TAFSIR VALUES(null, 'يصرعه و يضرب به الأرض' , 341, 1);
INSERT INTO TAFSIR VALUES(null, 'الجنون و الخبل ' , 342, 1);
INSERT INTO TAFSIR VALUES(null, 'يُهلك المال الذي يدخل فيه ' , 343, 1);
INSERT INTO TAFSIR VALUES(null, 'ينمّي المال الذي أُخرجَت منه' , 344, 1);
INSERT INTO TAFSIR VALUES(null, 'فأيقِنوا به ' , 345, 1);
INSERT INTO TAFSIR VALUES(null, ' ضيق الحال عُدْم المال ' , 346, 1);
INSERT INTO TAFSIR VALUES(null, 'فإمهال و تأخير واجب عليكم ' , 347, 1);
INSERT INTO TAFSIR VALUES(null, 'وليمل و ليقرّ' , 348, 1);
INSERT INTO TAFSIR VALUES(null, 'لا ينقص من الحقّ الذي عليه ' , 349, 1);
INSERT INTO TAFSIR VALUES(null, 'أن يملي و يقرّ بنفسه ' , 350, 1);
INSERT INTO TAFSIR VALUES(null, 'لا يمتنع ' , 351, 1);
INSERT INTO TAFSIR VALUES(null, 'لا تملّوا لا تضجروا ' , 352, 1);
INSERT INTO TAFSIR VALUES(null, 'أعدل ' , 353, 1);
INSERT INTO TAFSIR VALUES(null, 'أثبت لها و أعون على آدائها ' , 354, 1);
INSERT INTO TAFSIR VALUES(null, 'أقرب ' , 355, 1);
INSERT INTO TAFSIR VALUES(null, 'خروج عن الطاعة إلى المعصية ' , 356, 1);
INSERT INTO TAFSIR VALUES(null, 'نسألك مغفرتك ' , 357, 1);
INSERT INTO TAFSIR VALUES(null, 'طاقتها و ما تقدر عليه ' , 358, 1);
INSERT INTO TAFSIR VALUES(null, 'عبئاً ثقيلاً و هو التكاليف الشّاقّة ' , 359, 1);
INSERT INTO TAFSIR VALUES(null, 'لا قدرة لنا على القيام به ' , 360, 1);
